# Generated by Django 4.1.5 on 2023-01-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['ukończono']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='tytuł',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='ukończono',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='utworzono',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='użytkownik',
        ),
    ]
