# Generated by Django 4.1.5 on 2023-01-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_description_task_opis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ukończono',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='utworzono',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tytuł',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='użytkownik',
            new_name='user',
        ),
    ]
